FROM ubuntu:latest
WORKDIR /sync_server
RUN mkdir sync_server
COPY /bin/sync_server /sync_server/sync_server

RUN chmod +x sync_server/sync_server
RUN mkdir photos      
CMD ["sync_server/sync_server", "-p", "3000", "-d", "/photos/"]
EXPOSE 3000